### ISSUE TITLE
Non-mutable model field in GOSPEL

### ISSUE THREAD

**Issue by mariojppereira** [vocal-project/vocal#2]
Consider the following example, contained in file `test.mli`:
```
type t
(*@ model v: integer *)
```
When I run `gospel_tc test.mli` I get
```
 type t
    (*@ 
        mutable model v : integer *)
```
Also, in `gospel/ocaml-lib/tast.ml a field is defined as an `lsymbol`, which in turn is defined as
```
type lsymbol = {
  ls_name   : ident;
  ls_args   : ty list;
  ls_value  : ty option;
  ls_constr : bool;
}
```
so I have no way to test the mutability of a field.

Does this mean that fields are always considered mutable?

**Comment by belolourenco** [comment]
> Does this mean that fields are always considered mutable?

Yes, right now it means exactly that, but I'll make the change right now.
